var subcategories = [
    {
        Parent: "Housing",
        Topic: "Finding a Place to Live",
        Description: "This section provides information and resources for refugees on finding and maintaining affordable and safe housing.",
        Links: ["https://rentboard.ca", "https://chf.bc.ca", "https://bchousing.org/", "https://issbc.org"],
        Descriptions: ["The Rent Board Canada provides a comprehensive listing of rental properties available in British Columbia. You can search for rental properties by location, price range, number of bedrooms, and other factors.", "The Co-op Housing Federation of BC is a non-profit organization that helps low-income families and individuals access affordable housing through housing cooperatives.", "BC Housing is a government organization that provides affordable housing options and support services for eligible low-income residents in British Columbia. They have a wide range of housing options available, including rental housing and supportive housing for those who need extra assistance.","The Immigrant Services Society of BC provides support and resources for immigrants and refugees settling in British Columbia, including information and assistance on finding affordable housing."],
        Names: ["Rental Listings", "Co-op Housing Federation of BC", "BC Housing", "Settlement and Housing Services at ISSofBC"],
    },
    {
        Parent: "Housing",
        Topic: "Rent/Lease Agreements and Security Deposits",
        Description: "This section provides information on legal contracts for renting or leasing a property. Understand the terms, know your rights and responsibilities as tenants, seek assistance if needed.",
        Links: ["https://tenants.bc.ca", "https://gov.bc.ca/rentingbc", "https://issbc.org"],
        Descriptions: ["The Tenant Resource & Advisory Centre provides information and resources for tenants in British Columbia, including information on rent and lease agreements.", "The Government of British Columbia provides information and resources on renting in BC, including information on rent and lease agreements, rights and responsibilities of tenants and landlords, and dispute resolution.","The Immigrant Services Society of BC provides support and resources for immigrants and refugees settling in British Columbia, including information and assistance on finding affordable housing."],
        Names: ["Tenant Resource & Advisory Centre", "RentingBC", "Settlement and Housing Services at ISSofBC"],
    },
    {
        Parent: "Housing",
        Topic: "Maintenance and Repairs",
        Description: "This section outlines details regarding maintenance and repairs for ypur property. Learn about the responsibilities of landlords and tenants, and understand common maintenance and repair issues.",
        Links: ["https://tenants.bc.ca", "https://homesforgood.ca"],
        Descriptions: ["The Tenant Resource & Advisory Centre provides information and resources for tenants in British Columbia, including information on rent and lease agreements.","Homes for Good provides information and resources for tenants on maintenance and repairs in rental properties, including information on what to do if repairs are needed and how to request repairs from a landlord."],
        Names: ["Tenant Resource & Advisory Centre", "Homes for Good"],
    },
    {
        Parent: "Housing",
        Topic: "Eviction and Homelessness Prevention",
        Description: "This section provides information on eviction and homelessness, including the legal process of eviction, your rights as a tenant, and resources available to help find a new place to live.",
        Links: ["https://tenants.bc.ca/", "https://hsabc.ca/"],
        Descriptions: ["The Tenant Resource & Advisory Centre provides information and resources for tenants in British Columbia, including information on rent and lease agreements.","The Homelessness Services Association of BC provides information and resources on homelessness and eviction prevention in British Columbia, including information on support services and programs available to those at risk of homelessness."],
        Names: ["Tenant Resource & Advisory Centre", "Homelessness Services Association of BC"],
    },
    {
        Parent: "Culture & Community",
        Topic: "Understanding Canada's Culture",
        Description: "This section provides information on understanding the cultural norms and values of the host country as a refugee. Gain knowledge of local customs, traditions, and beliefs, learn about the local laws, and seek assistance from cultural advisors or mentors if needed.",
        Links: ["https://culturelink.ca/", "https://canada.ca/en/immigration-refugees-citizenship/services/canadians/celebrate-being-canadian/teachers-corner.html"],
        Descriptions: ["A Toronto-based organization that provides a range of services to help newcomers integrate into Canadian society, including information and resources on cultural norms and values. Although they are based in Toronto, they provide a wealth of information that can be useful to refugees anywhere in Canada.","The Teachers’ Corner offers you resources to teach citizenship, immigration and multiculturalism subjects. Share them with your students and colleagues as part of a lesson or to make learning more fun!"],
        Names: ["Tenant Resource & Advisory Centre", "Government of Canada: Teachers' Corner"],
    },
    {
        Parent: "Culture & Community",
        Topic: "Building a Social Network and Making New Friends",
        Description: "This section offers guidance on building a social network as a refugee. Learn about the challenges and opportunities, identify resources and support networks, and take proactive steps to cultivate meaningful connections in your new community.",
        Links: ["https://www.meetup.com", "https://mosaicbc.org/wp-content/uploads/2016/07/Volunteer-Opportunities-for-Newcomers.pdf", "https://issbc.org/job-types/become-a-volunteer"],
        Descriptions: ["An online platform that connects people with similar interests and helps them find events and activities to attend. There are a wide range of Meetup groups in BC, including groups for refugees and immigrants, where newcomers can meet other people, make new friends, and learn about life in their new communities","Volunteering is a great way to meet new people, build relationships, and get involved in the community. MOSAIC BC provides a list of volunteering opportunities for newcomers.", "Volunteering is a great way to meet new people, build relationships, and get involved in the community. The ISSofBC welcomes newcomers from all backgrounds as volunteers."],
        Names: ["Meetup", "MOSAIC BC Volunteering Opportunities for Newcomers", "ISSofBC Volunteer Connections Program"],
    },
    { 
        Parent: "Learn English",
        Topic: "Useful Tools for Learning English",
        Description: "This section highlights useful tools for refugees to learn English, including language-learning apps, online courses, and in-person resources. Improve your language skills, understand cultural nuances, and connect with language exchange partners. Find the support you need to succeed in your new home",
        Links: ["https://duolingo.com/", "https://babbel.com/", "https://memrise.com/", "https://www.bbc.co.uk/learningenglish", "#"],
        Descriptions : ["A popular language learning platform that offers courses in English and over 100 other languages. It’s free, fun, and accessible on any device with an internet connection.", "Another online language learning platform that offers courses in English and other languages. Babbel offers a variety of courses designed for different levels and learning styles.", "A language learning platform that uses spaced repetition and gamification to help learners retain information and progress quickly. Memrise offers courses in English and many other languages.", "A website provided by the British Broadcasting Corporation that offers free lessons, videos, and resources to help learners improve their English language skills.", "Start by learning the basics of the language, such as common greetings, basic vocabulary, and basic grammar structures. This will help you feel more confident when communicating with others and will provide a foundation for further language learning."],
        Names: ["Duolingo", "Babbel", "Memrise", "BBC Learning English", "Helpful Tip:"],
    },
    {
        Parent: "Learn English",
        Topic: "Language Instruction for Newcomers to Canada (LINC)",
        Description: "As a newcomer to Canada, learning English is one of the most important things you can do to make British Columbia feel like home. LINC English classes are delivered by qualified instructors and will equip newcomers with the English conversation skills needed to settle in Canada, make new connections, and find work. LINC classes improve reading, writing, listening, and speaking skills in English, while providing information on the local community, Canadian culture, and job search support.",
        Links: ["https://issbc.org/our-resource/register-for-linc", "https://douglascollege.ca/programs-courses/training-group/linc"],
        Descriptions: ["The ISSofBC provides a comprehensive video guide on how you can apply for LINC at your nearest assessment centre and offers free LINC classes at their Surrey location.", "LINC, offered at Douglas College delivers free language training and skills development services that will help you attain the English proficiency you need to function and participate in all aspects of Canadian society and the economy. "],
        Names: ['Applying for LINC', 'LINC at Douglas College'],
    },
    {
        Parent: "Mental Health",
        Topic: "Useful Websites on this Topic",
        Description: "This list compiles helpful websites on mental health that offer a wealth of resources and support. Gain insights into mental health conditions, access tools for self-care, connect with online communities, and seek professional help if necessary.",
        Links: ["https://cmha.ca", "https://camh.ca", "https://canada.ca/en/public-health/services/mental-health-support.html", "https://healthlinkbc.ca/health-topics/hw233861"],
        Descriptions: ["A nationwide organization that promots mental health and supports people recovering from mental illness", "The Centre for Addiction and Mental Health (CAMH) is Canada's largest mental health teaching hospital ", "The Government of Canada website provides resources on mental health support", "HealthLinkBC provides non-emergency care information to residents of British Columbia"],
        Names: ['Canadian Mental Health Association', 'Centre for Addiction and Mental Health', 'Government of Canada Mental Health Supports', 'HealthLinkBC'],
    },
    {
        Parent: "Mental Health",
        Topic: "Understanding Mental Health",
        Description: "This section provides information on understanding mental health. Learn about mental health conditions, recognize symptoms, understand treatment options, and seek support if needed.",
        Links: ["https://mentalhealthcommission.ca", "https://cmha.ca"],
        Descriptions: ["The Mental Health Commission of Canada provides information and resources on mental health, including what it is, how to maintain it, and how to access support.", "The Canadian Mental Health Association provides information and resources on mental health, including information on different types of mental health conditions and how to access support."],
        Names: ['The Mental Health Commission of Canada', 'Canadian Mental Health Association'],
    },
    {
        Parent: "Mental Health",
        Topic: "Managing Stress and Trauma",
        Description: "Mental health and wellness can be impacted by a range of factors, including genetics, life events, and stress. It's important to understand these factors and to seek support when needed to maintain good mental health and wellness.",
        Links: ["https://vastbc.ca", "https://bouncebackbc.ca"],
        Descriptions: ["VAST assists refugees and other newcomers who have endured torture, trauma and political violence through counselling, documentation, education, and referrals.", "BounceBack is a free skill-building program designed to help adults and youth 13+ manage low mood, mild to moderate depression, anxiety, stress or worry."],
        Names: ['Vancouver Association for Survivors of Torture', 'BounceBackBC'],
    },
    {
        Parent: "Mental Health",
        Topic: "Finding Support",
        Description: "If you're in need of mental health support in Canada or BC, there are many resources available to you. ",
        Links: ["tel:+8334564566", "tel:+8006686868", "https://mentalhealthsupport.net/", "https://cmha.ca"],
        Descriptions: ["Thinking of suicide? Call this number.", "More than a helpline. Call, text, chat and more to get support using Kids Help Phone's 24/7 e-mental health services. For all young people in Canada.More than a helpline. Call, text, chat and more to get support using Kids Help Phone's 24/7 e-mental health services. For all young people in Canada.", "The Mental Health Support Network provides a directory of mental health support resources, including support groups and mental health professionals, for individuals in British Columbia.", "The Canadian Mental Health Association provides information and resources on mental health, including information on different types of mental health conditions and how to access support."],
        Names: ['Canada Suicide Prevention Service 18334564566', 'Kids Help Phone 18006686868', 'Mental Health Support Network', 'Canadian Mental Health Association'],
    },
    {
        Parent: "Healthcare",
        Topic: "Understanding the Healthcare System",
        Description: "Refugees in BC can access a wide range of healthcare services and medical care through the publicly funded healthcare system. This system is known as the Medical Services Plan (MSP) and it provides coverage for a range of services, including hospital care, doctor visits, and diagnostic tests. To access these services, refugees must have a BC Services Card, which is a government-issued identification card that proves they are eligible for MSP coverage.",
        Links: ['https://www.health.gov.bc.ca/health-insurance', 'https://www.health.gov.bc.ca/health-insurance/overview', 'https://www.health.gov.bc.ca/health-insurance/understanding'],
        Names: ['Health Insurance BC', 'Health Insurance BC Overview', 'Health Insurance BC Understanding Your Coverage']
    },
    {
        Parent: "Healthcare",
        Topic: "Insurance and Coverage Options",
        Description: "Refugees in BC may also be eligible for other insurance coverage options, including private health insurance and supplemental insurance plans. Private health insurance may provide coverage for services not covered by MSP, such as dental and vision care.",
        Links: ['https://www.health.gov.bc.ca/health-insurance', 'https://www.health.gov.bc.ca/health-insurance/eligibilty', 'https://www.health.gov.bc.ca/health-insurance/enrolling'],
        Names: ['Health Insurance BC', 'Health Insurance BC Eligibility', 'Health Insurance BC Enrolling in Coverage']
    },
    {
        Parent: "Healthcare",
        Topic: "Preventative Care and Wellness",
        Description: "Preventative care and wellness is an important aspect of maintaining good health. To access preventative care services in BC, you can visit your doctor, a public health clinic, or a community health center. These providers can offer a range of services, including vaccinations, cancer screenings, and health assessments.",
        Links: ['https://www.healthlinkbc.ca/health-topics/hw233370', 'https://www.healthlinkbc.ca/health-topics/hw233380', 'https://www2.gov.bc.ca/gov/content/health/promoting-healthy-living/preventative-health'],
        Names: ['HealthLinkBC Wellness', 'HealthLinkBC Preventive Care', 'BC Ministry of Health - Preventative Health'],
    },
    {
        Parent: "Healthcare",
        Topic: "Chronic Conditions and Special Needs",
        Description: "If you have a chronic condition or special need, it is important to receive ongoing care and support to manage your condition. In BC, there are several resources available to help refugees with chronic conditions and special needs access healthcare services and medical care.",
        Links: ['https://www.healthlinkbc.ca/health-topics/hw233390', 'https://www.healthlinkbc.ca/health-topics/hw233401', 'https://www2.gov.bc.ca/gov/content/health/care-facility-administration-licensing/resident-care-standards/chronic-disease-management'],
        Names: ['HealthLinkBC Chronic Diseases', 'HealthLinkBC Disability Services and Supports', 'BC Ministry of Health - Chronic Disease Management'],
    },
    {
        Parent: "Healthcare",
        Topic: "Emergency and Urgent Care",
        Description: "In the event of an emergency or urgent medical situation, it is important to seek medical care as soon as possible. In BC, you can visit a hospital emergency room, call 9-1-1 for emergency medical services, or go to a walk-in clinic for urgent medical care.",
        Links: ['https://www.healthlinkbc.ca/health-topics/hw233440', 'tel:+911'],
        Names: ['HealthLinkBC Emergencies', '9-1-1'],
    },
    {
        Parent: "Legal Services",
        Topic: "Understanding the Legal System",
        Description: "This section aims to guide individuals in understanding the legal system. Familiarize yourself with legal terms, know your rights and responsibilities, and seek assistance if needed to navigate through the complexities of the legal system",
        Links: ["https://www.gov.bc.ca/ag", "https://www.cba.org", "https://www.canadianlegalfaq.ca"],
        Descriptions: ["The British Columbia Ministry of Attorney General provides information on the legal system in British Columbia, including information on accessing the courts and the services provided by the Legal Services Society.", "The Canadian Bar Association provides information and resources for individuals navigating the legal system in Canada, including information on finding a lawyer, legal procedures and court processes.","Canadian Legal FAQ provides basic information and answers to common questions about the Canadian legal system, including information on accessing the courts and finding a lawyer."],
        Names: ['BC Ministry of Attorney General', 'Canadian Bar Association', 'Canadian Legal FAQ'],
    },
    {
        Parent: "Legal Services",
        Topic: "Understanding the Legal System",
        Description: "This section aims to guide individuals in understanding the legal system. Familiarize yourself with legal terms, know your rights and responsibilities, and seek assistance if needed to navigate through the complexities of the legal system",
        Links: ["https://www.gov.bc.ca/ag", "https://www.cba.org", "https://www.canadianlegalfaq.ca"],
        Descriptions: ["The British Columbia Ministry of Attorney General provides information on the legal system in British Columbia, including information on accessing the courts and the services provided by the Legal Services Society.", "The Canadian Bar Association provides information and resources for individuals navigating the legal system in Canada, including information on finding a lawyer, legal procedures and court processes.","Canadian Legal FAQ provides basic information and answers to common questions about the Canadian legal system, including information on accessing the courts and finding a lawyer."],
        Names: ['BC Ministry of Attorney General', 'Canadian Bar Association', 'Canadian Legal FAQ'],
    },
    {
        Parent: "Legal Services",
        Topic: "Finding a Lawyer",
        Description: "This section aims to guide individuals in understanding the legal system. Familiarize yourself with legal terms, know your rights and responsibilities, and seek assistance if needed to navigate through the complexities of the legal system",
        Links: ["https://www.lawsociety.bc.ca", "https://www.cba.org", "https://www.bc-ivmw.org", "https://clasbc.net", "https://www.accessprobono.ca"],
        Descriptions: ["The Law Society of British Columbia provides a directory of lawyers in British Columbia, allowing individuals to search for lawyers by name, location, or area of practice.", "The Canadian Bar Association provides information and resources for individuals navigating the legal system in Canada, including information on finding a lawyer, legal procedures and court processes.", "The BC Society of Immigrant and Visible Minority Women provides legal information, advice and representation to women of all backgrounds in British Columbia. They have a focus on immigration, family and refugee law.", "The Community Legal Assistance Society provides legal assistance to low-income individuals and marginalized communities in British Columbia. They have a focus on immigration and refugee law, as well as other areas of law that impact refugees.", "Access Pro Bono provides free legal services to individuals and non-profit organizations in British Columbia. They have a focus on serving those who cannot afford a lawyer, including refugees."],
        Names: ['Law Society of BC', 'Canadian Bar Association', 'The BC Society of Immigrant and Visible Minority Women', 'Community Legal Assistance Society', 'Access Pro Bono'],
    },
    {
        Parent: "Legal Services",
        Topic: "Court Procedures and Hearings",
        Description: "If a refugee is involved in a legal dispute, they may need to attend a court hearing. It can be helpful to understand the court procedures and what to expect at a hearing. The court process can be confusing, but there are resources available to help refugees navigate the system.",
        Links: ["https://www.gov.bc.ca/ag", "https://www.cba.org"],
        Descriptions: ["The British Columbia Ministry of Attorney General provides information on the legal system in British Columbia, including information on accessing the courts and the services provided by the Legal Services Society.", "The Canadian Bar Association provides information and resources for individuals navigating the legal system in Canada, including information on finding a lawyer, legal procedures and court processes."],
        Names: ['BC Ministry of Attorney General', 'Canadian Bar Association'],
    },
    {
        Parent: "Financial",
        Topic: "Basic Concepts and Terminology",
        Description: "Understanding basic financial concepts is crucial for refugees as they start to rebuild their financial lives in a new country. Some of the key concepts to understand include budgeting, saving, earning, and spending money, credit and debt, and investing. It’s also important to familiarize yourself with financial terms and concepts that are commonly used in Canada.",
        Links: ["https://www.investopedia.com/terms", "https://www.bankofcanada.ca/glossary", "https://www.fcac-acfc.gc.ca/eng/resources/publications/money/index-eng.html"],
        Names: ['Investopedia - Terms', 'Bank of Canada - Glossary', 'Financial Consumer Agency of Canada'],
    },
    {
        Parent: "Financial",
        Topic: "Budgeting and money management techniques",
        Description: "Budgeting is a critical component of managing your finances. It helps you keep track of your income and expenses, so you can see where your money is going and make changes to your spending habits. Some useful budgeting techniques include setting financial goals, creating a spending plan, and tracking your expenses. There are also many free budgeting tools and resources available online, such as the FCAC's budget calculator.",
        Links: [" https://moneymattersbc.ca/tools-and-resources/budgeting-and-money-management", "https://www.fcac-acfc.gc.ca/eng/resources/publications/budgeting/index-eng.html", "https://www.canada.ca/en/financial-consumer-agency/services/financial-education/budgeting.html"],
        Names: ['Money Matters BC - Budgeting', 'Financial Consumer Agency of Canada', 'Government of Canada'],
    },
    {
        Parent: 'Financial',
        Topic: 'Building and managing credit',
        Description: "Budgeting is a critical component of managing your finances. It helps you keep track of your income and expenses, so you can see where your money is going and make changes to your spending habits. Some useful budgeting techniques include setting financial goals, creating a spending plan, and tracking your expenses. There are also many free budgeting tools and resources available online, such as the FCAC's budget calculator.",
        Links: [" https://moneymattersbc.ca/tools-and-resources/budgeting-and-money-management", "https://www.fcac-acfc.gc.ca/eng/resources/publications/budgeting/index-eng.html", "https://borrowell.com", "https://www.creditkarma.ca/"],
        Names: ['Money Matters BC', 'Financial Consumer Agency of Canada', 'Borrowell', 'Credit Karma'],
    },
    {
        Parent: 'Financial',
        Topic: 'Accessing bank accounts, loans and insurance',
        Description: "Accessing financial products and services such as bank accounts, loans, and insurance can be challenging for refugees, especially if they do not have a credit history in Canada. However, there are many options available, such as no-credit check bank accounts, prepaid credit cards, and alternative lending options.",
        Links: [" https://moneymattersbc.ca/tools-and-resources/banking-and-insurance/", "https://www.fcac-acfc.gc.ca/eng/resources/publications/budgeting/index-eng.html", "https://www.canada.ca/en/financial-consumer-agency/services/financial-education/banking.html"],
        Names: ['Money Matters BC - Budgeting', 'Financial Consumer Agency of Canada', 'Government of Canada'],
    },
    {
        Parent: 'Settlement',
        Topic: 'Useful Websites for the Resettlement Process',
        Description: "This section provides digital resources for individuals seeking to understand and navigate the immigration and citizenship process.",
        Descriptions: ['The ISSofBC (Immigrant Services Society of British Columbia) is a non-profit organization that provides a range of services for new immigrants and refugees in BC, Canada.', 'MOSAIC is a non-profit organization that offers a variety of programs and services to immigrants and refugees in BC, Canada, to help them settle and integrate into Canadian society.', 'The Refugee Hub is a Canadian non-profit organization that provides information, resources, and support to refugees and new immigrants in Canada.', 'This website provides information and resources for individuals making a refugee claim in British Columbia, Canada.', 'This website is provided by the Government of Canada and provides a comprehansive directory of information and resources for newcomers to Canada, including refugees and immigrants.'],
        Links: ["https://issbc.org", "https://mosaicbc.org", "https://refugeehub.ca", "https://refugeeclaimbc.com", "https://www.canada.ca/en/immigration-refugees-citizenship/campaigns/newcomers.html"],
        Names: ['ISSofBC', 'MOSAIC', 'Canadian Refugee Hub', 'Refugee Claim BC', 'Government of Canada - Newcomers'],
    },
    {
        Parent: 'Settlement',
        Topic: 'Settlement Services and Programs',
        Description: "As a newcomer to British Columbia, it can be overwhelming to navigate all the different systems and services that are available. Settlement support helps you and your family to settle in your new community with confidence and ease.",
        Descriptions: ['WelcomeBC explains settlement services, and also provides a list of settlement service providers in British Columbia', 'The Settlement Orientation Services (SOS) program is designed specifically for refugee claimants, offering support and guidance throughout the claim process. This service can help to make the often-complex process of claiming asylum a little bit easier, and ensure that you have the information and resources you need to make a successful claim.', 'For newcomers who may be facing challenges adjusting to life in Canada, ISS of BC offers the Moving Ahead service. This service provides settlement and integration support, helping you overcome any obstacles you may be facing and successfully transition to life in your new community.'],
        Links: ["https://www.welcomebc.ca/Start-Your-Life-in-B-C/Settlement-Services", "https://issbc.org/our-services/sos-settlement-orientation-services", "https://issbc.org/our-services/moving-ahead"],
        Names: ['WelcomeBC - Settlement Services', 'ISSofBC SOS Program', 'ISSofBC Moving Ahead Program']
}]